# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/randymcmillan/dotfiles/nostril

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/randymcmillan/dotfiles/nostril

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/randymcmillan/dotfiles/nostril/CMakeFiles /Users/randymcmillan/dotfiles/nostril//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/randymcmillan/dotfiles/nostril/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named configurator

# Build rule for target.
configurator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 configurator
.PHONY : configurator

# fast build rule for target.
configurator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/build
.PHONY : configurator/fast

#=============================================================================
# Target rules for targets named nostril

# Build rule for target.
nostril: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nostril
.PHONY : nostril

# fast build rule for target.
nostril/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/build
.PHONY : nostril/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/Experimental.dir/build.make deps/secp256k1/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/Nightly.dir/build.make deps/secp256k1/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/Continuous.dir/build.make deps/secp256k1/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyMemoryCheck.dir/build.make deps/secp256k1/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyStart.dir/build.make deps/secp256k1/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyUpdate.dir/build.make deps/secp256k1/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyConfigure.dir/build.make deps/secp256k1/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyBuild.dir/build.make deps/secp256k1/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyTest.dir/build.make deps/secp256k1/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyCoverage.dir/build.make deps/secp256k1/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlyMemCheck.dir/build.make deps/secp256k1/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/NightlySubmit.dir/build.make deps/secp256k1/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalStart.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalUpdate.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalConfigure.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalBuild.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalTest.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalCoverage.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalMemCheck.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ExperimentalSubmit.dir/build.make deps/secp256k1/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousStart.dir/build.make deps/secp256k1/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousUpdate.dir/build.make deps/secp256k1/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousConfigure.dir/build.make deps/secp256k1/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousBuild.dir/build.make deps/secp256k1/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousTest.dir/build.make deps/secp256k1/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousCoverage.dir/build.make deps/secp256k1/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousMemCheck.dir/build.make deps/secp256k1/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/ContinuousSubmit.dir/build.make deps/secp256k1/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/CMakeFiles/check.dir/build.make deps/secp256k1/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named secp256k1_precomputed

# Build rule for target.
secp256k1_precomputed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1_precomputed
.PHONY : secp256k1_precomputed

# fast build rule for target.
secp256k1_precomputed/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/secp256k1_precomputed.dir/build.make deps/secp256k1/src/CMakeFiles/secp256k1_precomputed.dir/build
.PHONY : secp256k1_precomputed/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/secp256k1.dir/build.make deps/secp256k1/src/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/bench.dir/build.make deps/secp256k1/src/CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named bench_internal

# Build rule for target.
bench_internal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_internal
.PHONY : bench_internal

# fast build rule for target.
bench_internal/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/bench_internal.dir/build.make deps/secp256k1/src/CMakeFiles/bench_internal.dir/build
.PHONY : bench_internal/fast

#=============================================================================
# Target rules for targets named bench_ecmult

# Build rule for target.
bench_ecmult: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_ecmult
.PHONY : bench_ecmult

# fast build rule for target.
bench_ecmult/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/bench_ecmult.dir/build.make deps/secp256k1/src/CMakeFiles/bench_ecmult.dir/build
.PHONY : bench_ecmult/fast

#=============================================================================
# Target rules for targets named noverify_tests

# Build rule for target.
noverify_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 noverify_tests
.PHONY : noverify_tests

# fast build rule for target.
noverify_tests/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/noverify_tests.dir/build.make deps/secp256k1/src/CMakeFiles/noverify_tests.dir/build
.PHONY : noverify_tests/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/tests.dir/build.make deps/secp256k1/src/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named exhaustive_tests

# Build rule for target.
exhaustive_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exhaustive_tests
.PHONY : exhaustive_tests

# fast build rule for target.
exhaustive_tests/fast:
	$(MAKE) $(MAKESILENT) -f deps/secp256k1/src/CMakeFiles/exhaustive_tests.dir/build.make deps/secp256k1/src/CMakeFiles/exhaustive_tests.dir/build
.PHONY : exhaustive_tests/fast

aes.o: aes.c.o
.PHONY : aes.o

# target to build an object file
aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.o
.PHONY : aes.c.o

aes.i: aes.c.i
.PHONY : aes.i

# target to preprocess a source file
aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.i
.PHONY : aes.c.i

aes.s: aes.c.s
.PHONY : aes.s

# target to generate assembly for a file
aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.s
.PHONY : aes.c.s

base64.o: base64.c.o
.PHONY : base64.o

# target to build an object file
base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.o
.PHONY : base64.c.o

base64.i: base64.c.i
.PHONY : base64.i

# target to preprocess a source file
base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.i
.PHONY : base64.c.i

base64.s: base64.c.s
.PHONY : base64.s

# target to generate assembly for a file
base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.s
.PHONY : base64.c.s

configurator.o: configurator.c.o
.PHONY : configurator.o

# target to build an object file
configurator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.o
.PHONY : configurator.c.o

configurator.i: configurator.c.i
.PHONY : configurator.i

# target to preprocess a source file
configurator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.i
.PHONY : configurator.c.i

configurator.s: configurator.c.s
.PHONY : configurator.s

# target to generate assembly for a file
configurator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.s
.PHONY : configurator.c.s

nostril.o: nostril.c.o
.PHONY : nostril.o

# target to build an object file
nostril.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.o
.PHONY : nostril.c.o

nostril.i: nostril.c.i
.PHONY : nostril.i

# target to preprocess a source file
nostril.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.i
.PHONY : nostril.c.i

nostril.s: nostril.c.s
.PHONY : nostril.s

# target to generate assembly for a file
nostril.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.s
.PHONY : nostril.c.s

sha256.o: sha256.c.o
.PHONY : sha256.o

# target to build an object file
sha256.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.o
.PHONY : sha256.c.o

sha256.i: sha256.c.i
.PHONY : sha256.i

# target to preprocess a source file
sha256.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.i
.PHONY : sha256.c.i

sha256.s: sha256.c.s
.PHONY : sha256.s

# target to generate assembly for a file
sha256.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.s
.PHONY : sha256.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... check"
	@echo "... bench"
	@echo "... bench_ecmult"
	@echo "... bench_internal"
	@echo "... configurator"
	@echo "... exhaustive_tests"
	@echo "... nostril"
	@echo "... noverify_tests"
	@echo "... secp256k1"
	@echo "... secp256k1_precomputed"
	@echo "... tests"
	@echo "... aes.o"
	@echo "... aes.i"
	@echo "... aes.s"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... configurator.o"
	@echo "... configurator.i"
	@echo "... configurator.s"
	@echo "... nostril.o"
	@echo "... nostril.i"
	@echo "... nostril.s"
	@echo "... sha256.o"
	@echo "... sha256.i"
	@echo "... sha256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

