#!/usr/bin/env bash

for relay in $(gnostr-get-relays -s);do
echo $relay
./gnostr-nip --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight)$relay) | gnostr-post-event --relay $relay & sleep 1 || true
nostril --sec $(gnostr-sha256 $(gnostr-weeble)$(gnostr-blockheight)$relay) \
--kind 30617 \
--tag d "$(gnostr-sha256 nostril)" \
--tag name "<human-readable project name>" \
--tag description "brief human-readable project description>" \
--tag web "<url for browsing>" \
--tag web "<url for browsing>" \
--tag clone "<url for git-cloning>" \
--tag clone "<url for git-cloning>" \
--tag clone "<url for git-cloning>" \
--tag relays "$relay" \
--tag r $(git rev-parse --short HEAD~0) \
--tag r $(git rev-parse         HEAD~0) \
--tag topic $(git rev-parse         HEAD~0) \
--tag maintainers "<other-recognized-maintainer>" \
--tag maintainers "<other-recognized-maintainer>"  \
-t gnostr \
-t $relay \
-t $(gnostr-weeble) \
-t $(gnostr-blockheight) \
-t $(gnostr-wobble) \
--content "$(gnostr-weeble)/$(gnostr-blockheight)/$relay/$(git rev-parse HEAD~0)" | \
gnostr-post-event --relay $relay & sleep 2; \
done
