name: macos-pre-release

# Controls when the action will run.
on:
  push:
    branches:
      - 'master'
      - '**pre-release**'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-release:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
          set-safe-directory: 'true'
      - name: printenv && brew install rustup-init automake libtool cmake scdoc || sudo apt update && sudo apt install scdoc -y || true
        run: |
          printenv && brew install rustup-init automake libtool cmake scdoc || sudo apt update && sudo apt install scdoc -y || true
      - name: "Build pre-release"
        run: |
          sudo mkdir -p /usr/local/share/man/man1/nostril.1
          make nostril
          mv nostril nostril-$RUNNER_OS-$RUNNER_ARCH
          shasum -a 256 nostril-$RUNNER_OS-$RUNNER_ARCH > nostril-$RUNNER_OS-$RUNNER_ARCH.sha256.txt
          mv nostril-query nostril-query-$RUNNER_OS-$RUNNER_ARCH
          shasum -a 256 nostril-query-$RUNNER_OS-$RUNNER_ARCH > nostril-query-$RUNNER_OS-$RUNNER_ARCH.sha256.txt
          ls -a
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ !env.ACT }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: true
          title: "Development Build"
          files: |
            nostril-*
      - name: cargo install gnostr-bins gnostr-xq
        run: |
          cargo install gnostr-bins gnostr-xq
      - name: "make xcodebuild-install"
        run: |
          sudo make xcode xcodebuild xcodebuild-install
          ./build/Release/nostril --sec $(gnostr-sha256) | gnostr-post-event
